node('ussjo-dckr-ngp') {

  stage('python build'){
    docker.image('python:2-alpine').inside('-v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock -v "$HOME":/home') {
        echo 'hello'
        sh 'python --version'
    }
  }


}